<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Robot Properties -->
    <xacro:property name="base_length" value="0.6"/>
    <xacro:property name="base_width" value="0.4"/>
    <xacro:property name="base_height" value="0.2"/>
    
    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_width" value="0.05"/>
    <xacro:property name="caster_radius" value="0.05"/>
    
    <!-- Colors -->
    <material name="blue">
        <color rgba="0 0 0.8 1"/>
    </material>
    
    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <!-- Dummy Link (to fix inertia warning) -->
    <link name="dummy_link"/>

    <!-- Base Link -->
    <joint name="dummy_joint" type="fixed">
        <parent link="dummy_link"/>
        <child link="base_link"/>
    </joint>
    
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="5.0"/>
            <inertia ixx="0.0395" ixy="0" ixz="0" iyy="0.086" iyz="0" izz="0.0125"/>
        </inertial>
    </link>

    <!-- Right Wheel -->
    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.5"/>
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        </inertial>
    </link>

    <!-- Right Wheel Joint -->
    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-base_width/2 - wheel_width/2} ${-base_height/2 + wheel_radius}" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <!-- Left Wheel -->
    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.5"/>
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        </inertial>
    </link>

    <!-- Left Wheel Joint -->
    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${base_width/2 + wheel_width/2} ${-base_height/2 + wheel_radius}" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <!-- Caster Wheel -->
    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.1"/>
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
        </inertial>
    </link>

    <!-- Caster Joint -->
    <joint name="caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel"/>
        <origin xyz="${base_length/3} 0 ${-base_height/2 + caster_radius - 0.01}" rpy="0 0 0"/>
    </joint>

    <!-- Laser Scanner Link -->
    <link name="laser_scanner">
        <visual>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.1"/>
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
        </inertial>
    </link>

    <!-- Laser Scanner Joint -->
    <joint name="laser_scanner_joint" type="fixed">
        <parent link="base_link"/>
        <child link="laser_scanner"/>
        <origin xyz="0 0 ${base_height/2 + 0.02}" rpy="0 0 0"/>
    </joint>

</robot>
